@base = http://localhost:8022/api/v1/billing

### Public Manifest
GET {{base}}/docs

### Public Doc by slug
GET {{base}}/docs/gamelift-overview

### Internal Manifest
GET {{base}}/internal/docs

### Internal Doc by slug
GET {{base}}/internal/docs/s3-architecture-overview


### Health
GET http://localhost:8022/health




### Health
POST http://localhost:8022/api/v1/billing/card
Content-Type: application/json
Accept: application/json

{
  "cardholderName": "John Doe",
  "cardNumber": "4242424242424242",
  "expirationMonth": "12",
  "expirationYear": "2028",
  "cvv": "123",
  "address": "123 Nairobi Street",
  "city": "Nairobi",
  "state": "Nairobi",
  "zipCode": "00100"
}


### Health
POST http://localhost:8022/api/v1/billing/mpesa/stk-push
Content-Type: application/json
Accept: application/json

{
    "phone":"254704847676",
    "accountName":"Martin Karani"
}

### Get All Billings
GET {{base}}/billings

### Get Billing By Service
GET {{base}}/services/ec2